/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mediaplayertest;

import java.awt.List;
import java.awt.image.BufferedImage; //colormode
import java.io.File; //upload file
import java.io.IOException; //untuk penentuan jenis data seperti jpg
import java.sql.Blob; //untuk mengambil type data blob pada database
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level; //jenis user
import java.util.logging.Logger; //pencatatan waktu
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog; //error
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author A
 */
public class FormAdmin extends javax.swing.JFrame {
    
    Blob blob;
    BufferedImage img;
    
    Koneksi konek = new Koneksi();
    
    int id_terpilih;
    
    FormAdmin upload;
    int row_terpilih;
    String[] getdata_edit = new String[8];
    
    Connection conn;
    Statement pstmt;
    ResultSet rs;
    PreparedStatement ps;
    
    /**
     * Creates new form formAdmin1
     */
    public FormAdmin(FormAdmin upload, int row_terpilih, String id_terpilih, String title, int year, String genre, String director, String actor, String country, String synopsis ) {
        initComponents();
        this.id_terpilih= Integer.parseInt(id_terpilih);
        this.upload = upload;
        this.row_terpilih = row_terpilih;
        
        title1.setText(title);
        year1.setSelectedIndex(year);
        director1.setText(director);
        actor1.setText(actor);
        country1.setText(country);
        synopsis1.setText(synopsis);
        
   
        
    }

    FormAdmin() {
    initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_home = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btn_LogOut = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_choose = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        director = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        actor = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        country = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        synopsis = new javax.swing.JTextArea();
        btn_upload = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btn_choose1 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        title1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jLabel35 = new javax.swing.JLabel();
        director1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        actor1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        country1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        synopsis1 = new javax.swing.JTextArea();
        btn_update = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        year1 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setText("search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, 30));

        Search.setBackground(new java.awt.Color(204, 204, 255));
        Search.setText("search");
        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 70, 30));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action", "Animation", "Family", "Fantasy", "Film-noir", "Music", "Musical", "Romance", "Western", "War", " " }));
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 123, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Genre");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 60, 30));

        table_home.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title", "Year", "Actor/Actress"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(table_home);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 630, 190));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel26.setText("Movies");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, 30));

        jLabel27.setFont(new java.awt.Font("Felix Titling", 1, 28)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("HOME");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 130, 60));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/movie icon.png"))); // NOI18N
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        btn_LogOut.setText("LOGOUT");
        btn_LogOut.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 102, 0), null));
        btn_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 90, 40));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/siapatauperlu22.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 640, 530));

        jTabbedPane1.addTab("Home", jPanel1);

        jPanel4.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Felix Titling", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("WATCH LATER");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(40, 10, 260, 50);

        jTextField2.setText("search");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField2);
        jTextField2.setBounds(0, 70, 130, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("search");
        jPanel4.add(jButton2);
        jButton2.setBounds(140, 70, 70, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "Title A-Z" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox2);
        jComboBox2.setBounds(520, 70, 110, 30);

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD, jLabel4.getFont().getSize()+6));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Movies");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(0, 110, 640, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title", "Year", "Actor/Actress"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(0, 160, 630, 190);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Sort by");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(460, 70, 70, 30);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/movie icon.png"))); // NOI18N
        jPanel4.add(jLabel29);
        jLabel29.setBounds(0, 10, 42, 42);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/siapatauperlu22.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(0, -80, 640, 640);

        jTabbedPane1.addTab("Watch Later", jPanel4);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("HISTORY");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 220, 50));

        jTextField1.setText("search");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("search");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 70, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "Title A-Z" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 110, 30));

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()+6));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Movies");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 640, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title", "Year", "Actor/Actress"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 630, 190));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Sort by");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 60, 30));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/movie icon.png"))); // NOI18N
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/siapatauperlu22.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 640, 500));

        jTabbedPane1.addTab("History", jPanel3);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(255, 255, 255));
        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        label3.setPreferredSize(new java.awt.Dimension(100, 24));
        label3.setText("Pertanyaan yang sering diajukan");
        jPanel5.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 270, 30));

        jLabel9.setBackground(new java.awt.Color(153, 51, 0));
        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Saya mengalami masalah masuk ke situs dengan username / password");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 560, 60));

        jLabel14.setBackground(new java.awt.Color(204, 51, 0));
        jLabel14.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Siapa yang bisa menambahkan data ke judul?");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 560, 60));

        jLabel15.setBackground(new java.awt.Color(204, 51, 0));
        jLabel15.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Bagaimana menghitung rating untuk sebuah film?");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 560, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/siapatauperlu22.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 640, 520));

        jTabbedPane1.addTab("Help", jPanel5);

        jPanel2.setLayout(null);

        btn_choose.setText("Choose");
        btn_choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chooseActionPerformed(evt);
            }
        });
        jPanel2.add(btn_choose);
        btn_choose.setBounds(70, 0, 90, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Cover :");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 0, 60, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Title :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 30, 40, 15);

        title.setText("...");
        jPanel2.add(title);
        title.setBounds(70, 30, 190, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Year :");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 70, 40, 15);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Genre :");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 100, 50, 15);

        jCheckBox1.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox1.setText("Action");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jCheckBox1.setName(""); // NOI18N
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(70, 100, 90, 19);

        jCheckBox2.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox2.setText("Horror");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox2);
        jCheckBox2.setBounds(70, 160, 90, 23);

        jCheckBox3.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox3.setText("Advanture");
        jPanel2.add(jCheckBox3);
        jCheckBox3.setBounds(180, 100, 90, 23);

        jCheckBox4.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox4.setText("Animation");
        jPanel2.add(jCheckBox4);
        jCheckBox4.setBounds(300, 100, 90, 23);

        jCheckBox5.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox5.setText("Comedy");
        jPanel2.add(jCheckBox5);
        jCheckBox5.setBounds(70, 130, 90, 23);

        jCheckBox6.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox6.setText("Crime");
        jPanel2.add(jCheckBox6);
        jCheckBox6.setBounds(520, 100, 90, 23);

        jCheckBox7.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox7.setText("Documantary");
        jPanel2.add(jCheckBox7);
        jCheckBox7.setBounds(180, 130, 90, 23);

        jCheckBox8.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox8.setText("Family");
        jPanel2.add(jCheckBox8);
        jCheckBox8.setBounds(300, 130, 90, 23);

        jCheckBox9.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox9.setText("Biography");
        jPanel2.add(jCheckBox9);
        jCheckBox9.setBounds(400, 100, 90, 23);

        jCheckBox10.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox10.setText("Thriller");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox10);
        jCheckBox10.setBounds(300, 190, 90, 23);

        jCheckBox11.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox11.setText("Fantasy");
        jPanel2.add(jCheckBox11);
        jCheckBox11.setBounds(400, 130, 90, 23);

        jCheckBox12.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox12.setText("Music");
        jPanel2.add(jCheckBox12);
        jCheckBox12.setBounds(180, 160, 90, 23);

        jCheckBox13.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox13.setText("War");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox13);
        jCheckBox13.setBounds(400, 190, 90, 23);

        jCheckBox14.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox14.setText("Sport");
        jPanel2.add(jCheckBox14);
        jCheckBox14.setBounds(180, 190, 90, 23);

        jCheckBox15.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox15.setText("Sci-fi");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox15);
        jCheckBox15.setBounds(70, 190, 90, 23);

        jCheckBox16.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox16.setText("History");
        jPanel2.add(jCheckBox16);
        jCheckBox16.setBounds(520, 130, 90, 23);

        jCheckBox17.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox17.setText("Musical");
        jPanel2.add(jCheckBox17);
        jCheckBox17.setBounds(300, 160, 90, 23);

        jCheckBox18.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox18.setText("Mistery");
        jPanel2.add(jCheckBox18);
        jCheckBox18.setBounds(400, 160, 90, 23);

        jCheckBox19.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox19.setText("Romance");
        jPanel2.add(jCheckBox19);
        jCheckBox19.setBounds(520, 160, 90, 23);

        jCheckBox20.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox20.setText("Westren");
        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox20);
        jCheckBox20.setBounds(520, 190, 90, 23);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Director :");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 230, 60, 15);

        director.setText("...");
        jPanel2.add(director);
        director.setBounds(70, 230, 200, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Actor :");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 270, 50, 15);

        actor.setText("...");
        jPanel2.add(actor);
        actor.setBounds(70, 270, 200, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Country :");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(10, 310, 60, 15);

        country.setText("...");
        jPanel2.add(country);
        country.setBounds(70, 310, 200, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Synopsis :");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 350, 60, 15);

        synopsis.setColumns(20);
        synopsis.setRows(5);
        jScrollPane1.setViewportView(synopsis);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(70, 350, 330, 70);

        btn_upload.setText("Upload");
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });
        jPanel2.add(btn_upload);
        btn_upload.setBounds(70, 440, 70, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(".jpg");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(160, 0, 40, 20);

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2014", "2015", "2016", "2017" }));
        jPanel2.add(year);
        year.setBounds(70, 70, 90, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/siapatauperlu22.jpg"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, -170, 650, 730);

        jTabbedPane1.addTab("Upload", jPanel2);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(null);

        btn_choose1.setText("Choose");
        btn_choose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choose1ActionPerformed(evt);
            }
        });
        jPanel7.add(btn_choose1);
        btn_choose1.setBounds(70, 0, 90, 20);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Cover :");
        jPanel7.add(jLabel31);
        jLabel31.setBounds(10, 0, 60, 20);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Title :");
        jPanel7.add(jLabel32);
        jLabel32.setBounds(10, 30, 40, 15);

        title1.setText("...");
        jPanel7.add(title1);
        title1.setBounds(70, 30, 190, 30);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Year :");
        jPanel7.add(jLabel33);
        jLabel33.setBounds(10, 70, 40, 15);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Genre :");
        jPanel7.add(jLabel34);
        jLabel34.setBounds(10, 100, 50, 15);

        jCheckBox21.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox21.setText("Action");
        jCheckBox21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jCheckBox21.setName(""); // NOI18N
        jCheckBox21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox21ActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBox21);
        jCheckBox21.setBounds(70, 100, 90, 19);

        jCheckBox22.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox22.setText("Horror");
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBox22);
        jCheckBox22.setBounds(70, 160, 90, 23);

        jCheckBox23.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox23.setText("Advanture");
        jPanel7.add(jCheckBox23);
        jCheckBox23.setBounds(180, 100, 90, 23);

        jCheckBox24.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox24.setText("Animation");
        jPanel7.add(jCheckBox24);
        jCheckBox24.setBounds(300, 100, 90, 23);

        jCheckBox25.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox25.setText("Comedy");
        jPanel7.add(jCheckBox25);
        jCheckBox25.setBounds(70, 130, 90, 23);

        jCheckBox26.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox26.setText("Crime");
        jPanel7.add(jCheckBox26);
        jCheckBox26.setBounds(520, 100, 90, 23);

        jCheckBox27.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox27.setText("Documantary");
        jPanel7.add(jCheckBox27);
        jCheckBox27.setBounds(180, 130, 90, 23);

        jCheckBox28.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox28.setText("Family");
        jPanel7.add(jCheckBox28);
        jCheckBox28.setBounds(300, 130, 90, 23);

        jCheckBox29.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox29.setText("Biography");
        jPanel7.add(jCheckBox29);
        jCheckBox29.setBounds(400, 100, 90, 23);

        jCheckBox30.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox30.setText("Thriller");
        jCheckBox30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox30ActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBox30);
        jCheckBox30.setBounds(300, 190, 90, 23);

        jCheckBox31.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox31.setText("Fantasy");
        jPanel7.add(jCheckBox31);
        jCheckBox31.setBounds(400, 130, 90, 23);

        jCheckBox32.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox32.setText("Music");
        jPanel7.add(jCheckBox32);
        jCheckBox32.setBounds(180, 160, 90, 23);

        jCheckBox33.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox33.setText("War");
        jCheckBox33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox33ActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBox33);
        jCheckBox33.setBounds(400, 190, 90, 23);

        jCheckBox34.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox34.setText("Sport");
        jPanel7.add(jCheckBox34);
        jCheckBox34.setBounds(180, 190, 90, 23);

        jCheckBox35.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox35.setText("Sci-fi");
        jCheckBox35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox35ActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBox35);
        jCheckBox35.setBounds(70, 190, 90, 23);

        jCheckBox36.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox36.setText("History");
        jPanel7.add(jCheckBox36);
        jCheckBox36.setBounds(520, 130, 90, 23);

        jCheckBox37.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox37.setText("Musical");
        jPanel7.add(jCheckBox37);
        jCheckBox37.setBounds(300, 160, 90, 23);

        jCheckBox38.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox38.setText("Mistery");
        jPanel7.add(jCheckBox38);
        jCheckBox38.setBounds(400, 160, 90, 23);

        jCheckBox39.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox39.setText("Romance");
        jPanel7.add(jCheckBox39);
        jCheckBox39.setBounds(520, 160, 90, 23);

        jCheckBox40.setBackground(new java.awt.Color(153, 51, 0));
        jCheckBox40.setText("Westren");
        jCheckBox40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox40ActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBox40);
        jCheckBox40.setBounds(520, 190, 90, 23);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Director :");
        jPanel7.add(jLabel35);
        jLabel35.setBounds(10, 230, 60, 15);

        director1.setText("...");
        jPanel7.add(director1);
        director1.setBounds(70, 230, 200, 30);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Actor :");
        jPanel7.add(jLabel36);
        jLabel36.setBounds(10, 270, 50, 15);

        actor1.setText("...");
        jPanel7.add(actor1);
        actor1.setBounds(70, 270, 200, 30);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Country :");
        jPanel7.add(jLabel37);
        jLabel37.setBounds(10, 310, 60, 15);

        country1.setText("...");
        jPanel7.add(country1);
        country1.setBounds(70, 310, 200, 30);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Synopsis :");
        jPanel7.add(jLabel38);
        jLabel38.setBounds(10, 350, 60, 15);

        synopsis1.setColumns(20);
        synopsis1.setRows(5);
        jScrollPane5.setViewportView(synopsis1);

        jPanel7.add(jScrollPane5);
        jScrollPane5.setBounds(70, 350, 330, 70);

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel7.add(btn_update);
        btn_update.setBounds(70, 440, 70, 30);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText(".jpg");
        jPanel7.add(jLabel39);
        jLabel39.setBounds(160, 0, 40, 20);

        year1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2014", "2015", "2016", "2017" }));
        jPanel7.add(year1);
        year1.setBounds(70, 70, 90, 20);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/siapatauperlu22.jpg"))); // NOI18N
        jPanel7.add(jLabel40);
        jLabel40.setBounds(0, -170, 650, 730);

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 630));

        jTabbedPane1.addTab("Update", jPanel6);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void btn_chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chooseActionPerformed
        
    }//GEN-LAST:event_btn_chooseActionPerformed

    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
        // TODO add your handling code here:
        String jdl = title.getText();
        int thn = year.getSelectedIndex();
        String drctr = director.getText();
        String actr = actor.getText();
        String cntry = country.getText();
        String snpss = synopsis.getText();
        String temp = "";
        
        
        if (jCheckBox1.isSelected()) {temp += jCheckBox1.getText();temp+= ", ";}
        if (jCheckBox2.isSelected()) {temp += jCheckBox2.getText();temp+= ", ";}
        if (jCheckBox3.isSelected()) {temp += jCheckBox3.getText();temp+= ", ";}
        if (jCheckBox4.isSelected()) {temp += jCheckBox4.getText();temp+= ", ";}
        if (jCheckBox5.isSelected()) {temp += jCheckBox5.getText();temp+= ", ";}
        if (jCheckBox6.isSelected()) {temp += jCheckBox6.getText();temp+= ", ";}
        if (jCheckBox7.isSelected()) {temp += jCheckBox7.getText();temp+= ", ";}
        if (jCheckBox8.isSelected()) {temp += jCheckBox8.getText();temp+= ", ";}
        if (jCheckBox9.isSelected()) {temp += jCheckBox9.getText();temp+= ", ";}
        if (jCheckBox10.isSelected()) {temp += jCheckBox10.getText();temp+= ", ";}
        if (jCheckBox11.isSelected()) {temp += jCheckBox11.getText();temp+= ", ";}
        if (jCheckBox12.isSelected()) {temp += jCheckBox12.getText();temp+= ", ";}
        if (jCheckBox13.isSelected()) {temp += jCheckBox13.getText();temp+= ", ";}
        if (jCheckBox14.isSelected()) {temp += jCheckBox14.getText();temp+= ", ";}
        if (jCheckBox15.isSelected()) {temp += jCheckBox15.getText();temp+= ", ";}
        if (jCheckBox16.isSelected()) {temp += jCheckBox16.getText();temp+= ", ";}
        if (jCheckBox17.isSelected()) {temp += jCheckBox17.getText();temp+= ", ";}
        if (jCheckBox18.isSelected()) {temp += jCheckBox18.getText();temp+= ", ";}
        if (jCheckBox19.isSelected()) {temp += jCheckBox19.getText();temp+= ", ";}
        if (jCheckBox20.isSelected()) {temp += jCheckBox20.getText();temp+= ", ";}
        
        showMessageDialog(null, temp);
//        if (jCheckBox1.isSelected()) {
//         showMessageDialog(null, "cobadulu");   
//        }
//        List<String> infos = new ArrayList<String>();
//        for (JCheckBox checkBox : JCheckBox) {
//            if (checkBox.isSelected()) {
//                infos.add(checkBox.getText());
//            }
//        }
        
        
    }//GEN-LAST:event_btn_uploadActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btn_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogOutActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan LogOut ?","Konfirmasi", JOptionPane.INFORMATION_MESSAGE);
            if (result == JOptionPane.YES_OPTION){
                new LogIn().setVisible(true);
                this.dispose(); 
            }
    }//GEN-LAST:event_btn_LogOutActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        Connection conn = konek.connect();
    
        try{
            PreparedStatement pstmt = conn.prepareStatement("Select * from Movie where id_movie=?");
            pstmt.setInt(1, id_terpilih);
            ResultSet rs = pstmt.executeQuery();
            if(rs.getInt("id_movie")==0){
                showMessageDialog(null, "Data tidak ada!!!");
            }
            else{
                int result = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data ini?","Hapus Data Movie", JOptionPane.INFORMATION_MESSAGE);
                if (result == JOptionPane.OK_OPTION){
                     String sql = "DELETE FROM Movie WHERE id_movie=?";
                     PreparedStatement hapus = conn.prepareStatement(sql);
                    // set the corresponding param
                    hapus.setInt(1, id_terpilih);
                    hapus.executeUpdate();
                    selectAll();
                    hapus.close();
                    }   
            }
            rs.close();
            pstmt.close();
            conn.close();
        } catch (SQLException e){
            System.out.println(e.getMessage());
            
    }
        
        /**if(row_terpilih != -1){
            String id_terpilih = table_home.getModel().getValueAt(row_terpilih, 0).toString();
            int selectedOption = JOptionPane.showConfirmDialog(null, "Do you want to delete this data? ", "Data deleted", JOptionPane.YES_NO_OPTION);
            if(selectedOption == JOptionPane.YES_OPTION){
                delete(Integer.parseInt(id_terpilih));
                showMessageDialog(null, "Data deleted success!");
                selectAll();
            }
        }**/
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btn_choose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_choose1ActionPerformed

    private void jCheckBox21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox21ActionPerformed

    private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox22ActionPerformed

    private void jCheckBox30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox30ActionPerformed

    private void jCheckBox33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox33ActionPerformed

    private void jCheckBox35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox35ActionPerformed

    private void jCheckBox40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox40ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        String title = title1.getText();
        int year = year1.getSelectedIndex();
        String director = director1.getText();
        String actor = actor1.getText();
        String country = country1.getText();
        String synopsis = synopsis1.getText();
        
        update (id_terpilih, title, year, director, actor, country, synopsis);
        showMessageDialog(null, "Data tidak ditemukan!");
        
        this.dispose();
    }//GEN-LAST:event_btn_updateActionPerformed

    
    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel MyTable = new DefaultTabelModel();
        MyTable.addColumn("TITLE");
        MyTable.addColumn("YEAR");
        MyTable.addColumn("GENRE");
        try(Connection conn = konek.connect()){
        String sql = "Select * from Movie Where Title LIKE '"+title.getText()+"%' "
                + "and Year LIKE '"+year.getSelectedIndex()+"%'";
        pstmt=conn.createStatement();
        rs=pstmt.executeQuery(sql);
        while(rs.next()){
            MyTable.addRow(new Object[]{
            rs.getString(1),
            rs.getString(2),
            rs.getString(3),
            });
        }
        table_home.setModel(MyTable);
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
        /**try(Connection conn = konek.connect()){
            if(search.getText() == title.getText()){
                String sql = "Select * from Movie where title like '%" + search.getText();
            }else if(search.getText().trim().isEmpty()){
                showMessageDialog(null,"Harus diisi");
            }
        }catch(SQLException e){
            
        }     **/
    }//GEN-LAST:event_SearchActionPerformed
    
    public void update(int id_terpilih, String title, int year, String director, String actor, String country, String synopsis){
        String sql = "UPDATE Movie SET title = ? ," + "year = ? ," + "director = ? ," + "actor = ? ," + "country = ? ," + "synopsis = ? WHERE id_movie";
        try (Connection conn = konek.connect();
            PreparedStatement pstmt = conn.prepareStatement(sql)){
            pstmt.setString(1, title);
            pstmt.setInt(2, year);
            pstmt.setString(3, director);
            pstmt.setString(4, actor);
            pstmt.setString(5, country);
            pstmt.setString(6, synopsis);
            pstmt.executeUpdate();
            
            pstmt.close();
            conn.close();
    } catch(SQLException e){
            System.out.println(e.getMessage());
            
    }
    }
    /**public void delete(int id_terpilih){
        Connection conn = konek.connect();
        String sql = "DELETE FROM Movie WHERE id_movie = ?";
        
        try(PreparedStatement pstmt = conn.prepareStatement(sql)){
            pstmt.setInt(1, id_terpilih);
            ResultSet rs = pstmt.executeQuery();
            if(rs.getInt("id_movie")==0){
                showMessageDialog(null, "Data tidak ada!!!");
            }
            
            rs.close();
            pstmt.close();
            conn.close();
        } catch (SQLException e){
            System.out.println(e.getMessage());
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAdmin().setVisible(true);
            }
        });
    }
    
    public void selectAll(){
        try {
            Connection conn = konek.connect();
            PreparedStatement pstmt = conn.prepareStatement("Select id_movie, title, year, actor, directory, country, synopsis from Movie");
            pstmt.setString(1, title.getText());
            pstmt.setInt(2, year.getSelectedIndex());
            pstmt.setString(3, director.getText());
            pstmt.setString(4, actor.getText());
            pstmt.setString(5, country.getText());
            pstmt.setString(6, synopsis.getText());
            
            ResultSet rs = pstmt.executeQuery();
              
             //To remove previously added rows
            while(table_home.getRowCount() > 0) 
            {
                ((DefaultTableModel) table_home.getModel()).removeRow(0);
            }

            while (rs.next()) {
                //Count the number of column
                
                ResultSetMetaData md = rs.getMetaData();
                int columns = md.getColumnCount();
                
                Object[] row = new Object[columns];
                for (int i = 1; i <= columns; i++)
                {  
                    row[i - 1] = rs.getObject(i);
                }
                ((DefaultTableModel) table_home.getModel()).insertRow(rs.getRow()-1,row);
                
            }
            
            // Tutup koneksi
            rs.close();
            pstmt.close();
            conn.close();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        
        
    }
            /**String sql = "SELECT id_movie, title, year, director, actor, country, synopsis FROM Movie";
            try(Connection conn = konek.connect();
                    Statement stmt = conn.createStatement();
                    ResultSet rs = stmt.executeQuery(sql)){
                
                while(table_home.getRowCount() > 0)
                {
                    ((DefaultTableModel) table_home.getModel()).removeRow(0);
                }
                while (rs.next()){
                    ResultSetMetaData md = rs.getMetaData();
                    int columns = md.getColumnCount();
                    
                        Object[] row = new Object[columns];
                        for (int i = 1; i <= columns; i++)
                        {
                            row[i-1] = rs.getObject(i);
                            System.out.println(rs.getObject(i));
                        }
                        ((DefaultTableModel) table_home.getModel()).insertRow(rs.getRow()-1,row);
                }
                rs.close();
                stmt.close();
            } catch (SQLException e){
                System.out.println(e.getMessage());
            }
    }**/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JTextField actor;
    private javax.swing.JTextField actor1;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btn_LogOut;
    private javax.swing.JButton btn_choose;
    private javax.swing.JButton btn_choose1;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_upload;
    private javax.swing.JTextField country;
    private javax.swing.JTextField country1;
    private javax.swing.JTextField director;
    private javax.swing.JTextField director1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label3;
    private javax.swing.JTextField search;
    private javax.swing.JTextArea synopsis;
    private javax.swing.JTextArea synopsis1;
    private javax.swing.JTable table_home;
    private javax.swing.JTextField title;
    private javax.swing.JTextField title1;
    private javax.swing.JComboBox<String> year;
    private javax.swing.JComboBox<String> year1;
    // End of variables declaration//GEN-END:variables

    private static class DefaultTabelModel extends DefaultTableModel {

        public DefaultTabelModel() {
        }
    }
}
