/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mediaplayertest;

import db.Koneksi;
import java.awt.image.BufferedImage;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A
 */
public class FormUser extends javax.swing.JFrame {

    /**
     * Creates new form formUser1
     */
    Koneksi konek = new Koneksi();
    int paging = 0;
    Blob blob;
    BufferedImage img;
    
    Connection conn;
    Statement pstmt;
    ResultSet rs;
    PreparedStatement ps;
    
    public FormUser() {
        initComponents();
       tampilkan_data();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        search1 = new javax.swing.JTextField();
        Search1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btn_LogOut = new javax.swing.JButton();
        btn_addWL = new javax.swing.JButton();
        btn_detail = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_home = new javax.swing.JTable();
        prev = new javax.swing.JLabel();
        next = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_WL = new javax.swing.JTable();
        History = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        label3 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search1.setText("search");
        search1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search1MouseClicked(evt);
            }
        });
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        jPanel1.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, 30));

        Search1.setBackground(new java.awt.Color(204, 204, 255));
        Search1.setText("search");
        Search1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search1ActionPerformed(evt);
            }
        });
        jPanel1.add(Search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 70, 30));

        jLabel7.setFont(new java.awt.Font("Felix Titling", 1, 28)); // NOI18N
        jLabel7.setText("HOME");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 130, 70));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel8.setText("Movies");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/movie icon.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        btn_LogOut.setBackground(new java.awt.Color(204, 204, 204));
        btn_LogOut.setText("LOGOUT");
        btn_LogOut.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 102, 0), null));
        btn_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 90, 40));

        btn_addWL.setText("+ Watch Letter");
        btn_addWL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addWLActionPerformed(evt);
            }
        });
        jPanel1.add(btn_addWL, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 110, 30));

        btn_detail.setText("Detail");
        btn_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detailActionPerformed(evt);
            }
        });
        jPanel1.add(btn_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, 30));

        table_home.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Year", "Actor/Actress", "Rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_home.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_homeMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_home);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 630, 190));

        prev.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prev.setText("Previous");
        prev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prevMouseClicked(evt);
            }
        });
        jPanel1.add(prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        next.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        next.setText("Next");
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        jTabbedPane1.addTab("Home", jPanel1);

        jPanel4.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Felix Titling", 1, 28)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("WATCH LATER");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(40, 20, 260, 50);

        jTextField2.setText("search");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField2);
        jTextField2.setBounds(0, 70, 130, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("search");
        jPanel4.add(jButton2);
        jButton2.setBounds(140, 70, 70, 30);

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD, jLabel4.getFont().getSize()+6));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Movies");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(0, 120, 610, 30);

        table_WL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title", "Year", "Actor/Actress"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_WL);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(0, 160, 620, 190);

        History.setText("History");
        History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryActionPerformed(evt);
            }
        });
        jPanel4.add(History);
        History.setBounds(523, 70, 90, 30);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/movie icon.png"))); // NOI18N
        jPanel4.add(jLabel20);
        jLabel20.setBounds(0, 20, 42, 42);

        jTabbedPane1.addTab("Watch Later", jPanel4);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("HISTORY");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 220, 50));

        jTextField1.setText("search");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("search");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 70, 30));

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()+6));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Movies");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 620, 30));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title", "Year", "Actor/Actress"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 620, 190));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/movie icon.png"))); // NOI18N
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 50));

        jTabbedPane1.addTab("History", jPanel3);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPane3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane3.setText("We calculate movie ratings by averaging the rating results of the films obtained.");
        jScrollPane8.setViewportView(jTextPane3);

        jPanel5.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 560, 50));

        jLabel15.setBackground(new java.awt.Color(204, 51, 0));
        jLabel15.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("How to calculate rating for a movie?");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setOpaque(true);
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 560, 30));

        jTextPane2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane2.setText("We provide search feature. If you forget the movie title, you can search by movie genre, or movie year in the search field already provided.");
        jScrollPane7.setViewportView(jTextPane2);

        jPanel5.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 560, 60));

        jLabel14.setBackground(new java.awt.Color(204, 51, 0));
        jLabel14.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("I'm looking for a film, but can't remember the title. Can you help me?");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.setOpaque(true);
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 560, 30));

        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextPane1.setText("If you were not prompted to choose a password or don't remember the password for your membership, you can get a new one by navigating to the Log in page. Select \"Log In\" and then select \"Forgot Your Password\". You'll be sent a link to your registered email to reset your password.");
        jScrollPane6.setViewportView(jTextPane1);

        jPanel5.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 560, 70));

        jLabel9.setBackground(new java.awt.Color(204, 51, 0));
        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("I forgot my password. How do I login?");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setOpaque(true);
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 560, 30));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(255, 255, 255));
        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        label3.setPreferredSize(new java.awt.Dimension(100, 24));
        label3.setText("Frequently Asked Questions");
        jPanel5.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 270, 30));

        jTabbedPane1.addTab("Help", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search1ActionPerformed

    private void btn_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogOutActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin mengakhiri sesi ini?","Konfirmasi", JOptionPane.INFORMATION_MESSAGE);
            if (result == JOptionPane.YES_OPTION){
                new LogIn().setVisible(true); //untuk menampilkan form baru
                this.dispose(); //set form saat ini menjadi invisible
                }
    }//GEN-LAST:event_btn_LogOutActionPerformed

    private void Search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search1ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel MyTable = new FormUser.DefaultTabelModel();
        MyTable.addColumn("TITLE");
        MyTable.addColumn("YEAR");
        MyTable.addColumn("GENRE");
        try(Connection conn = konek.connect()){
        String sql = "Select * from Movie Where title LIKE '"+search1.getText()+"%' ";
                //+ "and year LIKE '"+year.getSelectedIndex()+"%'";
        pstmt=conn.createStatement();
        rs=pstmt.executeQuery(sql);
        while(rs.next()){
            MyTable.addRow(new Object[]{
            rs.getString(2),
            rs.getString(3),
            rs.getString(4),
            });
            System.out.println("sukseessss");
        }
        table_home.setModel(MyTable);
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_Search1ActionPerformed

    private void search1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search1MouseClicked
        // TODO add your handling code here:
        search1.setText("");
    }//GEN-LAST:event_search1MouseClicked

    private void HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryActionPerformed
        // TODO add your handling code here:
        //addHistory(table_watchlater.getString());
    }//GEN-LAST:event_HistoryActionPerformed

    private void btn_addWLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addWLActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_home.getModel();
        int row = table_home.getSelectedRow();
        Movie film = new Movie();
        film.setId((int)model.getValueAt(row, 0));
        film.setTitle((String)model.getValueAt(row, 1));
        int idFilm = film.getId();
        String jdl = film.getTitle();

        try(Connection conn = konek.connect()){
            String sqlSelect = "SELECT * FROM Movie WHERE id_movie=?";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sqlSelect);

            if(row != -1){
                insertWL(idFilm,User.getIdUser(),jdl);
                tampilan_WL();
            }
        } catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_addWLActionPerformed

    private void btn_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detailActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_home.getModel();
        int row = table_home.getSelectedRow();
        if(row != -1){
            Movie x = new Movie();
            x.setId((int)model.getValueAt(row, 0));
            x.setTitle((String)model.getValueAt(row, 1));
            System.out.println(x.getId()+" "+x.getTitle());
            String sql = "SELECT id_movie FROM Movie WHERE title";
            Detail y = new Detail(x);
            y.setVisible(true);
        }
    }//GEN-LAST:event_btn_detailActionPerformed

    private void table_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_homeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_homeMouseClicked

    private void prevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prevMouseClicked
        // TODO add your handling code here:
        paging = paging - 5;
        if(paging!=0){
            tampilkan_data();
        } else{
            prev.disable();
        }
    }//GEN-LAST:event_prevMouseClicked

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        // TODO add your handling code here:
        paging = paging + 5;
        tampilkan_data();
    }//GEN-LAST:event_nextMouseClicked

    public void addHistory(int movie, int user, String date){
        //int movie; 
        //int user; 
        //String date;
        //String sql = "SELECT id_movie, id_user, date FROM History";
        String sql = "INSERT INTO History(id_movie, id_user, date)" +
                "VALUES('" + movie + "','" + user + "','" + date + "')";
        try (Connection con = konek.connect();
            PreparedStatement pstmt = con.prepareStatement(sql)) {
            pstmt.executeUpdate();
              //selectAll();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void tampilkan_data(){
        DefaultTableModel user = (DefaultTableModel)table_home.getModel();
        
        while(user.getRowCount() > 0)
        {
            user.removeRow(0);
        }
        
        String sql = "SELECT title, year, actor FROM Movie";
        
        try (Connection conn = konek.connect();
             Statement stmt  = conn.createStatement();
             ResultSet rs    = stmt.executeQuery(sql)){
              
             //To remove previously added rows
            while(table_home.getRowCount() > 0) 
            {
                ((DefaultTableModel) table_home.getModel()).removeRow(0);
            }

            //Hitung jumlah kolom
            ResultSetMetaData md = rs.getMetaData();
            int columns = md.getColumnCount();
                
            while (rs.next()) {
                Object[] row = new Object[columns];
                for (int i = 1; i <= columns; i++)
                {  
                    row[i - 1] = rs.getObject(i);
                    System.out.println(rs.getObject(i));
                }
                ((DefaultTableModel) table_home.getModel()).insertRow(rs.getRow()-1,row);
            }
            // Tutup koneksi
            rs.close();
            stmt.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    
    }
    
    public void insertWL(int idFilm, int idPengguna, String title){
        String sql = "INSERT INTO WatchLetter(id_movie, id_user, title) VALUES ('" +idFilm+ "', '" +idPengguna+ "','" +title+ "')";
        try(Connection conn = konek.connect();
            PreparedStatement pstmt = conn.prepareStatement(sql)){
            pstmt.executeUpdate();
        } catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
    public void tampilan_WL(){
        
        DefaultTableModel user = (DefaultTableModel)table_WL.getModel();
        while(user.getRowCount() > 0){
            user.removeRow(0);
        }
        String sql = "SELECT title, year, actor FROM Movie WHERE id_movie = (SELECT id_movie FROM WatchLetter WHERE id_user =" +User.getIdUser()+ ")";
        
        try(Connection conn = konek.connect();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql)){
            
            while(table_WL.getRowCount()>0){
                ((DefaultTableModel) table_WL.getModel()).removeRow(0);
            }
            ResultSetMetaData md = rs.getMetaData();
            int columns = md.getColumnCount();
            while (rs.next()){
                Object[] row = new Object[columns];
                for (int i = 1; i <= columns; i++)
                {  
                    row[i - 1] = rs.getObject(i);
                    System.out.println(rs.getObject(i));
                }
                ((DefaultTableModel) table_WL.getModel()).insertRow(rs.getRow()-1,row);
            }
            rs.close();
            stmt.close();
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton History;
    private javax.swing.JButton Search1;
    private javax.swing.JButton btn_LogOut;
    private javax.swing.JButton btn_addWL;
    private javax.swing.JButton btn_detail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private java.awt.Label label3;
    private javax.swing.JLabel next;
    private javax.swing.JLabel prev;
    private javax.swing.JTextField search1;
    private javax.swing.JTable table_WL;
    private javax.swing.JTable table_home;
    // End of variables declaration//GEN-END:variables

private static class DefaultTabelModel extends DefaultTableModel {

        public DefaultTabelModel() {
        }
    }

}

