/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mediaplayertest;

import db.Koneksi;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author Oktriana Sidik
 */
public class LogIn extends javax.swing.JFrame {

    Koneksi konek = new Koneksi();
    int id_terpilih;
    /**
     * Creates new form log
     */
    public LogIn() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        btn_SignIn = new javax.swing.JButton();
        btn_Regis = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        emailMessage = new javax.swing.JLabel();
        pwdMessage = new javax.swing.JLabel();
        tombolForgot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 51, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sign In", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(100, 40, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(100, 100, 90, 30);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email);
        email.setBounds(190, 40, 150, 30);
        jPanel2.add(password);
        password.setBounds(190, 100, 150, 30);

        btn_SignIn.setBackground(new java.awt.Color(255, 255, 153));
        btn_SignIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_SignIn.setText("SIGN IN");
        btn_SignIn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                btn_SignInMouseDragged(evt);
            }
        });
        btn_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignInActionPerformed(evt);
            }
        });
        jPanel2.add(btn_SignIn);
        btn_SignIn.setBounds(190, 170, 120, 30);

        btn_Regis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Regis.setText("SIGN UP");
        btn_Regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegisActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Regis);
        btn_Regis.setBounds(340, 250, 100, 23);

        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("Don't have account?");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(340, 220, 120, 30);

        emailMessage.setBackground(new java.awt.Color(204, 204, 0));
        emailMessage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        emailMessage.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(emailMessage);
        emailMessage.setBounds(200, 70, 150, 30);

        pwdMessage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pwdMessage.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(pwdMessage);
        pwdMessage.setBounds(200, 130, 150, 20);

        tombolForgot.setForeground(new java.awt.Color(255, 255, 255));
        tombolForgot.setText("Forgot Password?");
        tombolForgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolForgotMouseClicked(evt);
            }
        });
        jPanel2.add(tombolForgot);
        tombolForgot.setBounds(20, 240, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 97, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void btn_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignInActionPerformed
        if(email.getText().trim().isEmpty() && password.getText().trim().isEmpty()){
            emailMessage.setText("Email harus diisi!");
            pwdMessage.setText("Password harus diisi!");
        }else{
            try{
                String uname = email.getText();
                char[] pwd = password.getPassword();
                String pass = new String(pwd);
                
                cek();
                User.setUsername(uname);
                
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
        }   
        new Screen().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_SignInActionPerformed

    private void btn_SignInMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SignInMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SignInMouseDragged

    private void tombolForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolForgotMouseClicked
        new Forgot().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tombolForgotMouseClicked

    private void btn_RegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegisActionPerformed
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_RegisActionPerformed

    public void cek(){
        String pass = password.getText();
        String passMD5 = null;
        try{
            MessageDigest md5 = MessageDigest.getInstance("MD5");
            byte[] tmp = pass.getBytes();
            md5.update(tmp);
            passMD5 = byteArrToString(md5.digest());
        } catch(NoSuchAlgorithmException e){
            showMessageDialog(null, e.getMessage());
        }
        
        String sql = "SELECT * FROM User WHERE name='" +email.getText()+ "' AND password='"+passMD5+"'";
        
        try(Connection conn = konek.connect();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql)){
            
            
            if(rs.next()){
                if(rs.getString("job").equals("User")){
                User.setIdUser(rs.getInt("id_user"));
                    System.out.println(User.getIdUser());
                    System.out.println("it's work");
                new FormUser().setVisible(true);
                this.dispose();
                } else if(rs.getString("job").equals("Admin")){
                    User.setIdUser(rs.getInt("id_user"));
                    System.out.println(User.getIdUser());
                    System.out.println("it's work");
                new Zeropages().setVisible(true);
                this.dispose();
                }
            }else {
                showMessageDialog(null, "Username atau Password salah!");
                email.setText("");
                password.setText("");
                email.requestFocus();
            }
        } catch (SQLException e){
            showMessageDialog(null, e);
        }
    }
       
    private static String byteArrToString(byte[] b){
        String res = null;
        StringBuffer sb = new StringBuffer(b.length * 2);
        for (int i = 0; i < b.length; i++){
           int j = b[i] & 0xff;
           if (j < 16) {
              sb.append('0');
           }
           sb.append(Integer.toHexString(j));
        }
        res = sb.toString();
        return res.toUpperCase();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>
        try{
            com.jtattoo.plaf.texture.TextureLookAndFeel.setTheme("Default", "Java Swing", "");
            UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
            SwingUtilities.updateComponentTreeUI(new LogIn());
        } finally{
            new LogIn().setVisible(true);
        }
        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Regis;
    private javax.swing.JButton btn_SignIn;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailMessage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel pwdMessage;
    private javax.swing.JLabel tombolForgot;
    // End of variables declaration//GEN-END:variables
}
